stages:
  - test

.venv:
  stage: test
  image: python:3.11-bookworm
  cache:
    paths:
      - venv
    key:
      files:
        - pyproject.toml  # not ideal, but let's see how it goes

  before_script:
    - python3 -m venv venv --system-site-packages
    - echo "Installing dev dependencies"
    - source venv/bin/activate
    - python3 -m pip install ".[dev]"

lint:
  extends: .venv
  script:
    -  source venv/bin/activate
    -  pre-commit run --all-files

pytest:
  extends: .venv
  script:
    - source venv/bin/activate
    - python -m pytest

workflow:
  rules:
    # Prevent skipped pipelines from commits authored by CI
    - if: $CI_COMMIT_TAG
      when: always
    - if: $CI_COMMIT_AUTHOR == "Gitlab CI <gitlab-ci@gitlab.aai.sh>"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_COMMIT_BRANCH == "main"
