stages:
  - test

variables:  # Change pip's cache directory to be inside the project directory since we can only cache local items.
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"
  MYPY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/mypy"
  RUFF_CACHE_DIR: "$CI_PROJECT_DIR/.cache/ruff"

.venv:
  stage: test
  image: python:3.11-bookworm
  cache:
    paths:
      - venv
      - .cache/pre-commit
      - .cache/mypy
      - .cache/ruff
    key: dev-deps.lock

  before_script:
    - python -m venv venv --system-site-packages
    - source venv/bin/activate
    - python -m pip install -r dev-deps.lock

lint:
  extends: .venv
  script:
    -  python -m pip install . --no-deps --force-reinstall
    -  pre-commit run --all-files

pytest:
  extends: .venv
  variables:
    LAKEFS_HOST: http://lakefs.10.32.16.101.nip.io
    LAKEFS_ACCESS_KEY_ID: mlopskit
    LAKEFS_SECRET_ACCESS_KEY: mlopskit
  script:
    - python -m pip install . --no-deps --force-reinstall
    - python -m pytest

workflow:
  rules:
    # Prevent skipped pipelines from commits authored by CI
    - if: $CI_COMMIT_TAG
      when: always
    - if: $CI_COMMIT_AUTHOR == "Gitlab CI <gitlab-ci@gitlab.aai.sh>"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_COMMIT_BRANCH == "main"
