repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-yaml
        exclude: "mkdocs.yml"
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --fix --exit-non-zero-on-fix
        language: system
        types_or: [python, pyi]
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        types_or: [python, pyi]
      - id: ty-check
        name: ty check
        entry: uv run ty check
        language: system
        types_or: [python, pyi]
        pass_filenames: false
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.15
    hooks:
      - id: uv-lock
        name: Lock project dependencies
  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.30.1
    hooks:
      - id: zizmor
        args: [--min-severity=medium]
