name: Install Python version using uv
description: Install uv and a target Python interpreter
inputs:
  pythonVersion:
    description: Python version to set up using uv
    required: true
runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    - name: Install Python interpreter
      run: uv python install ${{ inputs.pythonVersion }}
      shell: bash
    - name: Install the project
      run: uv sync --frozen --all-extras --dev
      shell: bash
