#!/bin/bash

set -ex

cd /tmp
LAKEFS_VERSION="0.112.1"
curl -fsSL -o lakefs.tgz https://github.com/treeverse/lakeFS/releases/download/v${LAKEFS_VERSION}/lakeFS_${LAKEFS_VERSION}_Linux_x86_64.tar.gz 
tar xf lakefs.tgz

cat > ~/.lakectl.yaml <<EOF
credentials:
    access_key_id: AKIAIOSFOLQUICKSTART
    secret_access_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
server:
    endpoint_url: http://127.0.0.1:8000
EOF

mkdir -p ~/.jupyter
cat > ~/.jupyter/jupyter_server_config.py <<EOF
c.ServerProxy.servers = {
   "lakefs": {
       "command": ["/tmp/lakefs", "run", "--quickstart"],
       "port": 8000,
       "timeout": 10,
       "environment": {
        "LAKEFS_INSTALLATION_USER_NAME": "quickstart",
        "LAKEFS_INSTALLATION_ACCESS_KEY_ID": "AKIAIOSFOLQUICKSTART",
        "LAKEFS_INSTALLATION_SECRET_ACCESS_KEY": "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
        "LAKEFS_STATS_ENABLED": "false",
        "LAKEFS_DATABASE_TYPE": "local",
        "LAKEFS_AUTH_ENCRYPT_SECRET_KEY": "THIS_MUST_BE_CHANGED_IN_PRODUCTION",
        "LAKEFS_BLOCKSTORE_TYPE": "local",
        "LAKEFS_LOGGING_OUTPUT": "/tmp/lakefs.log",
       },
   },
}
EOF
