#!/bin/bash

set -ex

# export LAKEFS_INSTALLATION_USER_NAME="quickstart"
# export LAKEFS_INSTALLATION_ACCESS_KEY_ID="AKIAIOSFOLQUICKSTART"
# export LAKEFS_INSTALLATION_SECRET_ACCESS_KEY="wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
# export LAKEFS_STATS_ENABLED="false"
# export LAKEFS_DATABASE_TYPE="local"
# export LAKEFS_AUTH_ENCRYPT_SECRET_KEY="THIS_MUST_BE_CHANGED_IN_PRODUCTION"
# export LAKEFS_BLOCKSTORE_TYPE="local"
# export LAKEFS_LOGGING_OUTPUT="/tmp/lakefs.log"

# nohup /tmp/lakefs run --quickstart >/dev/null 2>&1 &

exec "$@"
