credentials:
  access_key_id: AKIAIOSFOLQUICKSTART
  secret_access_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
metastore:
  glue:
    catalog_id: ""
  hive:
    db_location_uri: file:/user/hive/warehouse/
    uri: ""
server:
  endpoint_url: http://127.0.0.1:8000
